kind: pipeline
name: default

clone:
  depth: 1
  
steps:
- name: test
   image: alpine
   commands:
     - echo hi
   when:
      changeset:
        includes: [ OWNERS ]
        
- name: finisher
    image: alpine
    commands:
      - echo finished


trigger:
  branch:
    - master
